# Generated by Django 4.1 on 2022-12-15 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(choices=[('TN', 'Tank'), ('HL', 'Heal'), ('DD', 'Damagedealer'), ('TR', 'Trader'), ('GM', 'Guildmaster'), ('QG', 'Questgiver'), ('SM', 'Smith'), ('LE', 'Leatherer'), ('AL', 'Alchemist'), ('MA', 'Mage')], default=1, on_delete=django.db.models.deletion.CASCADE, to='board.category'),
            preserve_default=False,
        ),
    ]
