# Generated by Django 4.1 on 2022-12-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
